Repository G12-Wanderwave/Wanderwave, pull requests merged in 2024-04, with the labels that each got.

#99 90 profile and edit screen are integrated to the navigations actions
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/AppTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/EditProfileTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/MainPlaceHolderTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/ProfileTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/screens/MainPlaceHolder.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/navigation/NavigationActions.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/IconsActions.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/EditProfileScreen.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/MainPlaceHolder.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileScreen.kt
Labels: ui

#186 [BUGFIX] Fixing the main bug with player screen test
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/PlayerScreenTest.kt
Labels: bug

#177 Firebase mocking
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/ProfileConnectionTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/TrackConnectionTest.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/data/Beacon.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt
Labels: bug

#179 Firebase local database implementation
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/LocalRepositoryTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/BeaconScreenTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/EditProfileTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/MapScreenTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/ProfileTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/TrackListScreenTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconScreenViewModelTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModelTest.kt
  app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModelTest.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/di/ConnectionModule.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/AppDatabase.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/BeaconDao.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/BeaconEntity.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/LocalBeaconRepository.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/LocalProfileRepository.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/LocalTrackRepository.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/ProfileDao.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/ProfileEntity.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/TrackDao.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/localDb/TrackEntity.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/FirebaseConnection.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/ProfileConnection.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/TrackConnection.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/BeaconRepository.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/BeaconRepositoryImpl.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/FirebaseRepository.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/ProfileRepository.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/ProfileRepositoryImpl.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/TrackRepository.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/TrackRepositoryImpl.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconViewModel.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/MapViewModel.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt
  app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModel.kt
Labels: model
